######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 4 20:55:09 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS += \
             `pkg-config liblog4cxx --cflags`

QMAKE_LFLAGS += \
             `pkg-config liblog4cxx --libs`

# Input
SOURCES += main.cpp
