######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 8 12:21:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qcommandline.h test.h
SOURCES += main.cpp qcommandline.cpp test.cpp
