######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 8 14:34:41 2010
######################################################################

#CONFIG += debug no_keywords

QMAKE_LFAGS+=-lpthread
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
